### ISSUE TITLE
Publish retained message will be marked as faild  when QualityOfServiceLevel  greater than AtMostOnce

### ISSUE THREAD

**Issue by cqgis** [dotnet/MQTTnet#1428] opened 2022-06-14 08:51 UTC
When retained message  QualityOfServiceLevel is greater than  AtMostOnce  , when  client connected , send retained message will be mark as faild becusce "Publish packet has no packet identifier"

I think it should set packetIdentifier when retained message  published 

MqttClient.cs  +390
``` c#
 if (subscribeResult.RetainedMessages != null)
            {
                foreach (var retainedApplicationMessage in subscribeResult.RetainedMessages)
                {
                    var publishPacket = _packetFactories.Publish.Create(retainedApplicationMessage.ApplicationMessage);
                    if (publishPacket.QualityOfServiceLevel > MqttQualityOfServiceLevel.AtMostOnce)
                    {
                        publishPacket.PacketIdentifier = Session.PacketIdentifierProvider.GetNextPacketIdentifier();
                    }
                    Session.EnqueueControlPacket(new MqttPacketBusItem(publishPacket));
                }
            }

```

**Comment by chkr1011** [comment] 2022-06-15 19:45
Thanks for reporting the issue. Duplicate of #1434.

**Closed by chkr1011** 2022-06-15 19:45 UTC
Labels: bug
