### ISSUE TITLE
[Server] How can I process messages on the server side?

### ISSUE THREAD

**Issue by MarkFangmeyer** [dotnet/MQTTnet#1843] opened 2023-09-15 10:48 UTC
Based on the statement [here](https://github.com/dotnet/MQTTnet/wiki/Server): 

"The server is also able to process every application message which was published by any client. The event ApplicationMessageReceived will be fired for every processed message. It has the same format as for the client but additionally has the ClientId."

I would like to process messages on the server side. The latest version of MQTTnet doesn't support that. The server class does not include "ApplicationMessageReceived", nor options like "WithApplicationMessageInterceptor" and "WithSubscriptionInterceptor" (mentioned in the same wiki text).

I find this very confusing. The code doesn't seem to match with the wiki.

**Comment by rlkollman** [comment] 2023-09-15 12:30
Head over to the 'Samples' folder in the repo to see how to handle everything in the latest version.  A lot has been changed in the 4.x series, but is explained in this folder: https://github.com/dotnet/MQTTnet/tree/master/Samples.  The wiki contains methods for the 3.x version.

**Comment by SeppPenner** [comment] 2023-09-15 12:47
I think this is exactly a duplicate of what I was asking as well in https://github.com/dotnet/MQTTnet/issues/1842.

**Comment by SeppPenner** [comment] 2023-09-15 12:48
> Head over to the 'Samples' folder in the repo to see how to handle everything in the latest version. A lot has been changed in the 4.x series, but is explained in this folder: https://github.com/dotnet/MQTTnet/tree/master/Samples. The wiki contains methods for the 3.x version.

That is true, but the concerned scenario is not described in the samples either.

**Comment by SeppPenner** [comment] 2023-09-15 12:51
@MarkFangmeyer If you don't want to process only the messages of topics the server subscribed to (As I want to do in my issue), but want to process any message published on the server, you can do the following:

```csharp
this.mqttServer.InterceptingPublishAsync += this.InterceptPublish;

private async Task InterceptPublish(InterceptingPublishEventArgs args)
{
    if (args.ClientId == "Sepp")
    {
        args.ProcessPublish = false;
        return;
    }

    args.ProcessPublish = true;
}
```

**Comment by MarkFangmeyer** [comment] 2023-09-15 12:57
Found exactly that as well. ^^ Thanks! Looks like, InterceptingPublishEventArgs includes everything I need.

**Comment by SeppPenner** [comment] 2023-09-15 14:42
> Found exactly that as well. ^^ Thanks! Looks like, InterceptingPublishEventArgs includes everything I need.

No problem, glad to help.

**Closed by SeppPenner** 2023-09-15 14:42 UTC
Labels: feature-request

**Comment by ljzj2** [comment] 2025-11-29 02:44
how to edit the ReasonCode of it? the client 's reason code is Success I want to edit it.

> [@MarkFangmeyer](https://github.com/MarkFangmeyer) If you don't want to process only the messages of topics the server subscribed to (As I want to do in my issue), but want to process any message published on the server, you can do the following:
> 
> this.mqttServer.InterceptingPublishAsync += this.InterceptPublish;
> 
> private async Task InterceptPublish(InterceptingPublishEventArgs args)
> {
>     if (args.ClientId == "Sepp")
>     {
>         args.ProcessPublish = false;
>         return;
>     }
> 
>     args.ProcessPublish = true;
> }
> You can basically intercept the published messages right before they are published.
