### ISSUE TITLE
MQTTnet.Exceptions.MqttProtocolViolationException: Received packet 'PubAck: [PacketIdentifier=21584] [ReasonCode=]' at an unexpected time.

### ISSUE THREAD

**Issue by Doyle-net** [dotnet/MQTTnet#723] opened 2019-07-26 08:52 UTC
### Which project is your bug related to?
- [ √] ManagedClient

### To Reproduce
An error occurred while connecting to the mqtt service。
This problem exists with the latest version or 2.8.5
Using TCP
This error occurs when the program is running on Windows 7 sp1, but it is normal in Windows 10.

### Additional context / logging
> MQTTnet.Exceptions.MqttProtocolViolationException: Received packet 'PubAck: [PacketIdentifier=21584] [ReasonCode=]' at an unexpected time.

### Code example
```csharp
var options = new ManagedMqttClientOptionsBuilder()
		.WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
		.WithClientOptions(new MqttClientOptionsBuilder()
			.WithClientId(Guid.NewGuid().ToString())                            
			.WithTcpServer("127.0.0.1", 33382)
			.WithCredentials(brokerInfo.BrokerUser, brokerInfo.BrokerPassword)
			.WithCleanSession()
			.Build())
		.Build();
var mqttClient = new MqttFactory().CreateManagedMqttClient();
mqttClient.StartAsync(options);               
mqttClient.ConnectingFailedHandler = new FailedHandler();                
mqttClient.ConnectedHandler = new ConnectedHandler(lblWsState);
```

**Comment by chkr1011** [comment] 2019-07-26 18:01
Hi,
This is fixed in version 3.x. Do you have any change to upgrade?

Best regards
Christian

**Comment by Doyle-net** [comment] 2019-07-27 01:06
The same is true for upgrade 3.05

**Comment by chkr1011** [comment] 2019-07-27 07:52
Please share a code sample which contains the sending of messages. The error indicates that a PubAck was received but no one was waiting for it.

**Comment by SeppPenner** [comment] 2019-07-29 08:03
@Doyle-net Does this mean you fixed this issue and if yes how?

**Comment by dpsenner** [comment] 2020-01-05 09:42
I'm observing this with mqttnet 3.0.8. Steps to reproduce:

1. Start broker
1. Start application
1. Publish at regular intervals with QoS 2
1. Restart broker
1. Application reconnects

At this point, the application should continue publishing.

What happens instead in the `IMqttClientDisconnectedHandler`, the `MqttClientDisconnectedEventArgs` has the property `ClientWasConnected` set to `true` and the property `Exception` contains the following:

```text
MQTTnet.Exceptions.MqttProtocolViolationException: Received packet 'PubRec: [PacketIdentifier=412] [ReasonCode=]' at an unexpected time.
   at MQTTnet.PacketDispatcher.MqttPacketDispatcher.Dispatch(MqttBasePacket packet)
   at MQTTnet.Client.MqttClient.TryProcessReceivedPacketAsync(MqttBasePacket packet, CancellationToken cancellationToken)
```

The explanation to me is that the broker and the application suffers a split brain scenario. The broker wants to resume a (incomplete) qos 2 publish handshake while the application cannot do so because it forgot about it.

The only known workaround to me is to connect with a clean session flag. This however defeats the purpose of QoS 2.

**Comment by soitgoes** [comment] 2020-03-06 21:10
+1 Experiencing this in 3.0.8 within my app but don't have reproduction steps, but it doesn't recover.

**Comment by eosberdav** [comment] 2020-03-10 11:05
+1 with version in 3.0.8.
As a workaround we are just using QOS 0.

**Comment by hutpit** [comment] 2020-05-18 12:37
If it helps, I ran into this same issue using a Rabbit broker.  I also ran the client in code using V3.0.10.  I turned out the broker did not support QOS 2, so it was downgrading to QOS 1.  That meant that instead of sending the PUBREC packet in response to the publish packet it was sending back a PUBACK packet.  Since MQTTnet was expecting a PUBREC packet (followed by a PUBREL packet) and received a PUBACK it threw this exception (which is thrown any time it publishes QOS 1/2 packets and does not receive the correct broker response).  Downgrading to QOS 1 likely works since QOS 1 does not expect any response packet from a broker.
The error message actually shows it received a PUBACK in your case too, which implies your broker is also returning the wrong thing.
This issue was also observed by seeing other clients continually re-receive the same message.

**Comment by dpsenner** [comment] 2020-05-22 18:57
The mqtt broker for me is mosquitto on debian stretch, version 1.4.10-3+deb9u4.

**Comment by havalli** [comment] 2021-01-07 12:03
Any update on this bug? I have the same problem with the mqtt server in iobroker. MQTTnet version 3.0.13

**Comment by chkr1011** [comment] 2021-01-07 19:16
I will add some checks that a PUBREC from a previous connection will no longer throw this exception. I will check if a PUBREL can be sent indicating that the client doesn't know the message anymore.

**Comment by Programmer888** [comment] 2021-01-21 14:28
I am still running into this problem when trying to connect from an MQTTnet client to an MQTTnet server. Locally the server connection works fine, but if I deploy to an azure webservice I run into this error. I tried to use port 80 as well as 443

**Comment by chkr1011** [comment] 2021-01-23 10:57
Please try with RC6. The relevant change was not yet pushed to nuget...

**Comment by Kbij** [comment] 2021-02-01 13:24
I still have this bug, even with the latest git master branch (63ca6086d5e95de4930dc9211c597fee77e1542c : 30/01/2021)
I can reproduce this bug, with a heavy stress test (15000 topics, about 30 mqtt connecties to mosquitto server). My stress test will send a message on each of these 15000 topics, and wait for connected devices to repond (15000 response messages). When I run this test in my local lan, then everything is ok. But when the mosquitto (2.0.5) server is located on the internet, then i see this exception. And connections are dropped.
It could be that my stress test is a bit to heavy, but i would expect that the library can handle this kind of load ?

**Comment by dpsenner** [comment] 2021-04-08 06:15
@Kbij You may be testing something else. A simple test for this scenario would be to write a small application that subscribes to a topic with QoS 2 and publishes a message to the topic. Using the debugger add a breakpoint to MQTTnet so that you can terminate the application while the QoS 2 handshake of publish is still incomplete. On the next start, the application subscribes again with QoS 2 and the broker will resume the ongoing publish. If this works the publish four way handshake works as expected and the bug is fixed.

I do think that under normal conditions, it should be sufficient to cleanly shutdown an application and all of its components. I do believe that MqttNet could cleanly shutdown by no longer accepting incoming messages (so that no new 4 way handshake begins). Some applications may even require a clean shutdown protocol that informs other participants about its intent, but that it something that builds on top of it. For the scenarios that I use MqttNet this is not needed. It is preferable that the application resumes where it left off, i.e. by processing inflight messages upon restart.

**Comment by chkr1011** [comment] 2022-07-13 12:25
I will close this due to inactivity. Please test again with latest version 4.0 and reopen this ticket if the error persists.

**Closed by chkr1011** 2022-07-13 12:25 UTC
Labels: support

**Comment by SeppPenner** [comment] 2024-04-03 07:21
I can't explain how this happened, but we now have this issue as well with the latest version (Client and Server in use and both on `4.3.3.952`). In our use case, there is a custom version of https://github.com/microsoft/reverse-proxy in between that was reset yesterday. Afterwards (No idea why), the exception occured out of nowhere.

I guess, if we restart all MQTT related services, it will work again... The problem is, that I can't provide example code as the code is included in a really big code base. However, this still seems to be an issue after a random network abortion somewhere between the server and the client...
