### ISSUE TITLE
MqttClient hangs on ConnectAsync

### ISSUE THREAD

**Issue by fdundjer** [dotnet/MQTTnet#966] opened 2020-07-29 14:56 UTC
### Describe the bug
IMqttClient instance hangs on ConnectAsync when trying to connect to a MQTT server while internet connection is off.

### Which project is your bug related to?
- Client

### Basic Information
MQTTnet version: 3.0.11
Xamarin.Forms version: 4.7.0.1179
Platform: Android
Device: Samsung SM-G937F, Android 10 - API 29

### To Reproduce
1. Make sure that internet connection is off on a mobile device
2. Start application
3. Try to connect to a mqtt server
4. Application will hang on ConnectAsync method

### Expected behavior
- Client should cancel the operation and throw exception after cancellation is requested

### Code example 
```csharp
var serverIpAddress = "176.222.222.222";
var serverPort = 1883;
try
{
    if (!Uri.TryCreate($"http://{serverIpAddress}:{serverPort}", UriKind.Absolute, out var uri) ||
        !IPAddress.TryParse(uri.Host, out _))
    {
        return;
    }

    var clientOptions = new MqttClientOptionsBuilder()
        .WithClientId(Guid.NewGuid().ToString())
        .WithCredentials(string.Empty, string.Empty)
        .WithTcpServer(uri.Host, uri.Port)
        .Build();

    var client = _mqttFactory.CreateMqttClient();

    // Timeout is one second
    using (var cancellationToken = new CancellationTokenSource(TimeSpan.FromSeconds(1)))
    {
        // Client hangs on a line below
        await client.ConnectAsync(clientOptions, cancellationToken.Token).ConfigureAwait(false);
    }
}
catch (Exception e)
{
    // ignored
}
```

ps. Let me know if you need example application/code :)

**Comment by chkr1011** [comment] 2020-08-01 19:35
Do you have more details or a full solution which has this issue? I also use MQTTnet in a Xamarin application and I cannot reproduce the issue.

What exactly do you mean with "internet connection is off"? Is Wifi AND Cellular just deactivated? Or is no WiFi in range etc?

**Comment by xmaux72** [comment] 2020-09-22 21:20
it's a huge bug... any news?

**Comment by redradist** [comment] 2020-09-28 22:45
I have the same issue, but when Server is down then connection is hang up ...
When it will be fixed ? Is there any news ?

**Comment by redradist** [comment] 2020-09-29 08:21
@chkr1011 I have figured out that hanging up come in Debug mode for Xamarin application, seems like debugger use some thread that with addition with failed connection to broker hanging up

When I run application without debug mode, just tap on icon, it starts properly ...

Also when I add `_managedMqttClient.ConnectingFailedHandler` than even in Debug mode application works properly after connection is failed ...

**Comment by chkr1011** [comment] 2020-11-21 19:27
@redradist What dies "add" the connection failed handler? Do you have also some code in the handler or only attached?

**Comment by redradist** [comment] 2020-11-21 19:30
@chkr1011 Seems like this my issue was due to Rider IDE ... On Visual Studio issue is not reproducible

If you interested there is ticket for it https://youtrack.jetbrains.com/issue/RIDER-52622

**Comment by chkr1011** [comment] 2020-11-21 19:34
@fdundjer Sorry for the long delay. Is this issue still relevant? I am not sure how to solve this because this library only makes use of sockets. Probably it is required to check availability of network via Xamarin APIs first?

**Comment by ReikoLJ** [comment] 2021-10-20 10:37
> @fdundjer Sorry for the long delay. Is this issue still relevant? I am not sure how to solve this because this library only makes use of sockets. Probably it is required to check availability of network via Xamarin APIs first?

Though not a Xamarin specific issue, I'm having an issue with the ConnectAsync method just swallowing the thread if the broker is not available at that time. 
No exception is returned so I cannot handle this behaviour in code. It's a very straight forward setup using node-red as a temp broker. If that node-red broker isn't running the client just hangs forever which is something I definitely don't want when this is turned into production code with a real broker

` var factory = new MqttFactory();`
 `_mqttClient = factory.CreateMqttClient();`
 
 `var options = new MqttClientOptionsBuilder().WithTcpServer("localhost", 1883).Build();`
`await _mqttClient.ConnectAsync(options);`

**Comment by kwende** [comment] 2021-12-28 20:35
@ReikoLJ have a look at https://github.com/chkr1011/MQTTnet/pull/1318

**Comment by chkr1011** [comment] 2022-08-14 10:41
I assume this issue is fixed. If the issue still exists in the latest version 4 please reopen the ticket and try connecting with apps like MQTTnetApp to see if the library is the root cause of this issue.

**Closed by chkr1011** 2022-08-14 10:41 UTC
Labels: bug
