### ISSUE TITLE
V 4.3.1.873 =》V 4.3.2.930  No service for type 'MQTTnet.Server.MqttServer' has been registered

### ISSUE THREAD

**Issue by Canroc** [dotnet/MQTTnet#1890] opened 2023-12-05 03:24 UTC
### Describe your question
Program.cs
<img width="504" alt="1701746372915" src="https://github.com/dotnet/MQTTnet/assets/84954229/49d858ec-7afa-4b9d-a532-9ffa04156b8d">

register service
<img width="370" alt="1701746454834" src="https://github.com/dotnet/MQTTnet/assets/84954229/aed4b129-0108-41c6-8d95-8ac489810ecf">

application
![image](https://github.com/dotnet/MQTTnet/assets/84954229/e73b526c-9708-4d4c-a39e-e8390d379b21)

### Which project is your question related to?
- Server

**Comment by 296370493** [comment] 2023-12-05 03:33
Yes, I also encountered this problem

**Comment by SeppPenner** [comment] 2023-12-05 05:34
Duplicate of https://github.com/dotnet/MQTTnet/issues/1889.

**Comment by holychaos** [comment] 2023-12-06 02:32
I think the reason is this:
4.3.2.930:
![image](https://github.com/dotnet/MQTTnet/assets/7961697/ff8dbbeb-7c41-4f1f-8a89-feab8333448f)

4.3.1.873:
![image](https://github.com/dotnet/MQTTnet/assets/7961697/717285f7-909b-43da-b1e8-93584980db31)

'UseMqttServer' requires' MqttServer ', but 4.3.2.930 is changed to 'MqttHostedServer'

**Comment by holychaos** [comment] 2023-12-06 02:36
Also 'AddSingleton<MqttHostedServer>()' and 'AddHostedService<MqttHostedServer>()' seem to get two singleton instances of 'MqttHostedServer', I don't know if this makes a difference.

**Closed** 2023-12-09 07:37 UTC
Labels: question
