### ISSUE TITLE
Server sets MaximumQoS to wrong value in MQTTnet v4

### ISSUE THREAD

**Issue by andy1547** [dotnet/MQTTnet#1445] opened 2022-06-24 09:39 UTC
Firstly, I cannot see a way for the server to set this when generating a CONNACK packet in either v3 or v4 of the library:
- In v3 MqttConnAckPacketProperties.MaximumQoS is null, so the property would be omitted and the client would therefore assume Exactly Once is the max.
- In v4 MqttConnAckPacket.MaximumQoS is 0 so the property now gets included and client would parse as At Most Once.

We noticed this when upgrading the server from v3 to v4 as it broke our v3.0.9 clients with exception "Property ID 'MaximumQoS' is not supported for package type 'MqttConnAckPacket'", I've confirmed this client error is fixed in the latest v3 release (v3.1.12).

We also noticed Topic Alias Maximum was 655535 in v3, but omitted in v4. After reading the spec, I think v4 is doing the correct thing by omitting it (as Topic Alias is a ushort so max is 655535) as it saves on network bandwidth.

--------------------------------------------

Firstly I think the default for MaximumQoS should be ExactlyOnce (same as old behavior).

Secondly we'd like the ability to set MaximumQoS to At Least Once, we haven't had any success using ValidatingConnectionEventArgs.ResponseUserProperties as it just appends to the property list.

**Comment by chkr1011** [comment] 2022-06-24 16:51
Duplicate of #1442.

**Closed by chkr1011** 2022-06-24 16:51 UTC
Labels: bug
