### ISSUE TITLE
MqttManagedClient Disconnected Event Not Firing on Server.StopAsync

### ISSUE THREAD

**Issue by JerrodV** [dotnet/MQTTnet#342] opened 2018-06-29 21:19 UTC
Hello,
This may be related to https://github.com/chkr1011/MQTTnet/issues/259. If so, feel free to merge them.
The difference is he does not mention that it is occurring on the IManagedMqttClient disconnected event. All my tests assume the Server and Client are on the same machine, so network traffic/firewall should not be a consideration.

I have 2 console apps based on the wiki. One is acting as the server and the other as client(s) where the client code is based on IManagedMqttClient.

I can start the server, and a client. If I then disconnect the client using Client.StopAsync(), the servers Server_ClientDisconnected responds immediately. If I reconnect the client, Server_ClientConnected responds immediately.

However, if I stop the server (via Server.StopAsync()) the client does not respond the same. A considerable amount of time passes before the client realizes the server is not connected and fires Client_Disconnected. I would assume that occasionally the client pings the server as in a keepalive and this is when the disconnect is detected. If I close the server application entirely, the clients then respond immediately.

This is problematic because since the client is unaware of the disconnection, messages are sent to a black whole (are not queued) as if a connection exists when it does not.

Note that in machine to machine tests, I found that the disconnected events did not fire on either side using the same StopAsync functions even though the messaging worked as expected. However, I am not convinced this was not either network or firewall issues. 

Thanks for a great library. I believe I can improve on this using IMqttClient by writing my own message queuing routine, but thought I'd mention this in case it was important enough to track down.

**Comment by chkr1011** [comment] 2018-07-01 08:17
Hi,
which Version of the lib do you use? 
Best regards
Christian

**Comment by JanEggers** [comment] 2018-07-01 17:14
I added a test and verified it is broken in dev branch I will try to fix it

**Comment by chkr1011** [comment] 2018-07-01 17:43
What did you find? Is the adapter not properly closed?

**Comment by JanEggers** [comment] 2018-07-01 18:29
have a look at https://github.com/JanEggers/MQTTnet/tree/ServerShutdown I created a test and moved stuff around so the event is firing, but something is blocking for 12 seconds now and i didnt yet find what it is

**Comment by JanEggers** [comment] 2018-07-01 18:57
hmm seem there is a bug in networkstream :( 

https://github.com/dotnet/corefx/issues/24430

ill add a workaround from there

**Comment by iamoldli** [comment] 2018-07-09 06:58
I have the same problem in 2.8.0 and 2.8.1

**Comment by JTrotta** [comment] 2018-07-18 10:44
I got the same problem on 2.8.1, but did not understand if it has been solved, or not?
Thank you.

**Comment by puppetSpace** [comment] 2021-03-16 08:42
I still have this issue.
Using version 3.0.15 on dotnet5.0

My client can connect to the broker, but when I just close my console window, I get a bunch of socketexceptions and in between those I get some MqttExceptions

SocketExceptions: 
"An existing connection was forcibly closed by the remote host."
"An established connection was aborted by the software in your host machine"

MqttProtocolViolationException:
"MQTTnet.Exceptions.MqttProtocolViolationException: 'Reason codes and reason string for disconnect are only supported for MQTTv5.'"

MqttCommunicationException:
This exception was originally thrown at this call stack:
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    MQTTnet.Implementations.MqttTcpChannel.ReadAsync(byte[], int, int, System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    MQTTnet.Adapter.MqttChannelAdapter.ReadFixedHeaderAsync(System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    MQTTnet.Adapter.MqttChannelAdapter.ReceiveAsync(System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    ...
    [Call Stack Truncated]

this is my code for setting up the broker:
```
			_logger.LogInformation("Starting mqtt broker");
			var options = new MqttServerOptionsBuilder()
			.WithDefaultEndpoint()
			.WithEncryptionSslProtocol(System.Security.Authentication.SslProtocols.Tls12)
			.WithApplicationMessageInterceptor(async x =>
			{
				_logger.LogDebug($"NEW MESSAGE: {{Topic: {x.ApplicationMessage.Topic}, Message: {Encoding.UTF8.GetString(x.ApplicationMessage.Payload)}}} ");
				var publisMessage = new MessageReceivedNotification { Topic = x.ApplicationMessage.Topic, ClientId = x.ClientId, Message = Encoding.UTF8.GetString(x.ApplicationMessage.Payload) };
				await _broker.Publish(publisMessage);

				x.AcceptPublish = true;
			})
			.WithSubscriptionInterceptor(x =>
			{
				_logger.LogDebug($"NEW SUBSCRIPTION: {{ClientId: {x.ClientId}, Filters: {x.TopicFilter}}} ");
				x.AcceptSubscription = true;
			})
			.WithConnectionValidator(async x =>
			{
				_logger.LogDebug($"NEW CONNECTION: {{ClientId: {x.ClientId}, Endpoint: {x.Endpoint}}}, Client certificate subject: {x.ClientCertificate?.Subject}, " +
					$"Client certificate thumbprint: {x.ClientCertificate?.Subject}, Authentication method: { x.AuthenticationMethod}, Is Secure: { x.IsSecureConnection}, " +
					$"UserName: { x.Username}");
				_logger.LogInformation($"Client '{x.ClientId}' connected");

				if (_connectionManager.IsClientAlreadyConnected(x.ClientId))
				{
					_logger.LogInformation($"Client '{x.ClientId}' already connected.");
					x.ReasonCode = MQTTnet.Protocol.MqttConnectReasonCode.ClientIdentifierNotValid;
					return;
				}

				await _broker.Publish(new ConnectionNotification { ClientId = x.ClientId});


			}).WithDisconnectedInterceptor(x => {
				_logger.LogInformation($"Client '{x.ClientId}' disconnected");
				_broker.Publish(new DisconnectNotification { ClientId = x.ClientId });
			})
			.Build();


			_server = new MqttFactory().CreateMqttServer();
			await  _server.StartAsync(options);
```

**Comment by chkr1011** [comment] 2022-01-27 19:57
Closing this due to inactivity. If the issue is not solved or closing is a mistake please feel free to reopen it.

**Closed by chkr1011** 2022-01-27 19:57 UTC
