### ISSUE TITLE
I send a lot of data every second, which seems to be slow?

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/MQTTnet#1511] opened 2022-09-09 02:36 UTC
I try to send 20 pieces of data every second. It seems that sending will be delayed for a long time.

Is there any best way?

**Comment by gfoidl** [comment] 2022-09-09 08:54
Are you using the managed client?
Can you share more information so that this issue becomes actionable? With the info given nothing can be done, except refering to the https://github.com/dotnet/MQTTnet/wiki

**Comment by bbhxwl** [comment] 2022-09-09 12:15
> Are you using the managed client? Can you share more information so that [this issue becomes actionable](https://letmegooglethat.com/?q=how+to+write+a+good+bug+report)? With the info given nothing can be done, except refering to the https://github.com/dotnet/MQTTnet/wiki

![image](https://user-images.githubusercontent.com/26525599/189347780-c9b550a9-8a88-495c-908b-1d0752720991.png)
If you call this method frequently, there will be no error and no return value. I don't know why?

**Comment by chkr1011** [comment] 2022-09-16 21:34
From code perspective it looks okay to me. Which broker do you use? And why do you expect an error? If there was no error the message was transmitted. And what means "no return value"? The task always has a return value.

**Comment by fungiboletus** [comment] 2022-09-20 12:24
No problems using a mosquitto server on localhost, but I also notice some heavy slowness using the MQTT managed client connected to a remote mosquitto server. Clients such as mqtt.js have no issues.

**Comment by chkr1011** [comment] 2022-09-20 12:53
Do you experience the same slowness when not using the managed client (MqttClient instead)?

**Comment by fungiboletus** [comment] 2022-09-20 16:41
> Do you experience the same slowness when not using the managed client (MqttClient instead)?

Is there a chance that it can help? I'm running a bit out of time on a project and I found a workaround (a local MQTT bridge). But if it can likely help I will remove the bridge tomorrow, otherwise I will try to see if it helps in a few weeks 😊

**Comment by chkr1011** [comment] 2022-10-01 09:26
The managed client is currently being rewritten from scratch so that performance issues will no longer happen. I close this issue because I assume the problem is gone when using the regular client instead of the managed one.

**Closed by chkr1011** 2022-10-01 09:26 UTC
Labels: bug
