### ISSUE TITLE
Broker - WithConnectionValidator and WithApplicationMessageInterceptor about ClientCertificate

### ISSUE THREAD

**Issue by rcs88** [dotnet/MQTTnet#698] opened 2019-07-13 22:12 UTC
I am trying to validate the certificate (who is connecting) to see if the credentials are valid. By the WithConnectionValidator method but the ClientCertificate is Null always.

Already at the time of receiving the message I need to know who it is sending. And the only information I have is the ClientId that does not work either.

Any suggestion?

**Comment by SeppPenner** [comment] 2019-07-14 15:40
First of all: Which version do you use? In the latest version, there is the `.ConnectionValidator` handler: Check https://github.com/chkr1011/MQTTnet/wiki/Server#validating-mqtt-clients, please.

> Already at the time of receiving the message I need to know who it is sending. And the only information I have is the ClientId that does not work either.

Where do you need the information who sent the message? In the server? What you are looking for is https://github.com/chkr1011/MQTTnet/wiki/Server#intercepting-application-messages. If you want to get username or password, you need to either use the 3.0.6-alpha or wait for the next release (Check https://github.com/chkr1011/MQTTnet/issues/682).

**Comment by rcs88** [comment] 2019-07-14 15:43
I'm using the ConnectionValidator, I have specified it up there. Except that the certificate comes Null.

**Comment by SeppPenner** [comment] 2019-07-14 16:00
@rcs88 I was just asking because you wrote something about `WithConnectionValidator`, not `.ConnectionValidator`.

Do you use the latest version of the library?

**Comment by rcs88** [comment] 2019-07-15 10:08
Yes 3.0.5

**Comment by SeppPenner** [comment] 2019-07-15 10:10
Which environment are you using for the broker? AspNetCore, NetCore, UWP, NetStandard, Xamarin?

**Comment by rudacs** [comment] 2019-07-15 13:34
The problem is time to convert X509Certificate to X509Certificate2.
I've also seen this problem (.NET Framework 4.6), I made an adjustment and I'm going to do a pull.

**Comment by rudacs** [comment] 2019-07-15 13:37
On the WithApplicationMessageInterceptor, I also had to make an adjustment to bring the certificate, user, and password data in order to identify who was sending and change Payload.
I do not know if what I have changed will be accepted. But I'm going to do the Pull.

I am also making other adjustments that I have identified and which I need to expose.

**Comment by SeppPenner** [comment] 2019-07-16 05:53
> The problem is time to convert X509Certificate to X509Certificate2.
I've also seen this problem (.NET Framework 4.6), I made an adjustment and I'm going to do a pull.

This is fixed with your PR https://github.com/chkr1011/MQTTnet/pull/702, @rudacs. @chkr1011 has merged it, so I guess it will be available in the release of version 3.0.6.

For your second PR (https://github.com/chkr1011/MQTTnet/pull/703), you need to use the `SessionItems` to store your data (available from 3.0.6-beta1 or so), Check e.g. https://github.com/chkr1011/MQTTnet/wiki/Server#storing-data-in-the-session

**Closed** 2022-07-15 12:08 UTC
Labels: bug, support
